### ISSUE TITLE
Week 8 Day 3 - Enter the Blag-o-sphere - 

### ISSUE THREAD

**Issue by mdewey** [Britney-Diboll/Assignments#30]
# Enter the Blag-o-sphere

For today, we are going to blogging and practicing everything we have talk about. 

## Objectives
- Practice talking like a developer
- Revisit old assignments

## Explorer
- [x] Blog time. Choose a prompt from the following list
    - Using your own experience as inspiration, create a short list of `survival tricks` for a someone entering a boot camp 
    - Pick 1 topic that we have learned and create a blog post explaining it to a new developer
    - Blog about a struggle that you have encountered and overcame during your tenure here so far. 
    - Pick a new technology that we haven't hit yet (or won't) and create a intro blog for that. 

- [x] Algorithm Practice -- submit a `gist` of your solution for https://www.codewars.com/kata/form-the-minimum in C# or JavaScript

## Adventure
- [ ] Get caught up on any outstanding homework. 
- [ ] Go back and refactor an old project. 
- [ ] Pick an old AngularJS project that used an API, create an API for that project. Hook up your project to that API
- [ ] Submit a `gist` of the above kata in the other language 

## Epic
- [ ] Further our Hacker News model but creating an API that returns the data for the front page. This includes creating models that produce a valid database. 
- [ ] Create an angular app that consumes and displays the data using Bootstrap to format it.

**Comment by Britney-Diboll** [comment]
https://gist.github.com/Britney-Diboll/0d946a0ae49671bed865722e842ae5f9

https://medium.com/@britney.diboll/survival-guide-to-coding-bootcamp-56fe10ac135e

**Comment by mdewey** [comment]
![Awesome Work!](https://media3.giphy.com/media/GvGjMfhlNNWik/200w_d.gif)
